### ISSUE TITLE
Swift?

### ISSUE THREAD

**Issue by cannyboy** [jhurray/JHChainableAnimations#1]
Is there a way to get this working with Swift?

I can get it to compile by changing:

```
#import "NSBKeyframeAnimationFunctions/NSBKeyframeAnimationFunctions.h"
```

to:

```
#import "NSBKeyframeAnimationFunctions.h"
```

but attempting to animate a button:

```
button.moveX(50).animate(0.5)
```

doesn't compile.

**Comment by jhurray** [comment]
That path error is now gone if you are using cocoa pods. Swift is unexplored territory with this library I'm going to play with that today and I'll get back to you. I know that [Masonry](https://github.com/SnapKit/Masonry) and [Snapkit](https://github.com/SnapKit/Snapkit) live separately.

**Comment by jhurray** [comment]
Ok so in swift the chainable property blocks are interpreted a little differently.

button.moveX()(50).animate()(0.5) will do the job in swift.

Thanks for bringing this to my attention.

**Comment by cannyboy** [comment]
Thanks for the info. For future reference, animationCompletion can be set in two ways in Swift:

```
// 1
button.animationCompletion = {
   println("animation is over")
}
button.moveX()(50).animate()(0.5)

// 2
button.moveX()(50).animate()(0.5).animationCompletion = {
    println("animation is over")
}
```

**Comment by jhurray** [comment]
Wow thats pretty cool. I updated the readme to support that way. That works in Objective-C too. Technically its kinda hacky because if the animation duration is 0.0 its a race condition to set the animationCompletion but in 99% of instances that works fine. 

This also works

```
// 3
button.moveX()(50).animateWithCompletion()(0.5, {
       println("animation is over")
})
```

**Comment by mxcl** [comment]
In case it’s useful, with [PromiseKit](https://github.com/mxcl/PromiseKit) I have chainable objc without ugly swift by having separate swift and objc extensions and making a custom module map so that the swift and objc see the different interfaces.

Making an entirely separate project for swift/objc was not to my tastes at least.
