### ISSUE TITLE
Not working for UILabel

### ISSUE THREAD

**Issue by nsleader** [jhurray/JHChainableAnimations#10]
```
_counterLabel
    .wait(0.2)
    .makeScale(2)
    .spring
    .animate(0.8);
```

After calling this code, the label is shifted to the left and not scaling!

**Comment by jhurray** [comment]
Labels should be scaled with translations. If you check the views frame it is increased but the font didnt change and the text alignment didnt change. A full suite of translations is coming soon.

**Comment by jhurray** [comment]
Should work with transform scale. Pod version 1.3.0

**Comment by nsleader** [comment]
Thanks!
