### ISSUE TITLE
Repeat animation group?

### ISSUE THREAD

**Issue by abonham** [jhurray/JHChainableAnimations#11]
Is there an easy way to repeat an animation at the moment? It would be great to see something like `view.makeScale(2.0).repeat(4).animate(3.0)`.

**Comment by jhurray** [comment]
No but that is a good idea. The only caveat would be that chainable properties like makeX and makeSize wont work with repeats so they have to be used appropriately. I will add this in the next update.

**Comment by abonham** [comment]
Thinking about it, with the way [UIView setNumberOfRepeats] works, maybe view.makeScale(2.0).animateWithRepeat(3.0, 4) would make more sense?

**Comment by alejandroluengo** [comment]
Yes it will make much more sense. I think that  animate(time).loop also will be helpful

**Comment by jhurray** [comment]
Keep an eye out in the next week or so for a major release with this feature!

**Comment by jhurray** [comment]
Added in v2.0.0. Marking as closed
