### ISSUE TITLE
could add many frequently-used animations effects?

### ISSUE THREAD

**Issue by CharlinFeng** [jhurray/JHChainableAnimations#13]
i'm chinese,english is pool, thank you !!!!!

i like those animations: .spring  and .bounce

i have some Advices：
1. spring and bounce could give us Parameter，like this : .spring(.5f) .bouce(1.0f) ?? it will be more Flexible.

2.can you provide other frequently-used animations effects? like shake, fade,flash,
i know a framework named canvas,but it did not support iOS 7's autoLayout, it's useful，but has many bugs, i think your framework could replace it Completely.
canvas,you should know it: https://github.com/CanvasPod/Canvas

thank you very much!!!!!

**Comment by jhurray** [comment]
This is meant to be a low level library. If you want those effects please checkout a library like [DCAnimationKit](https://github.com/daltoniam/DCAnimationKit).

Or you could build your own!

``` objective-c
- (void) shake:(UIView *)view {
    CGFloat shakeDist = 20.0;
    view.moveX(shakeDist).thenAfter(0.2).
        moveX(-2*shakeDist).thenAfter(0.2).
        moveX(shakeDist*1.5).thenAfter(0.2).
        moveX(shakeDist*-0.5).animate(0.2);
}
```
