### ISSUE TITLE
Grow Action and Shrink Chain not working

### ISSUE THREAD

**Issue by confile** [jhurray/JHChainableAnimations#15]
I want to grow (scale) a view set a new value and then shrink (scale) the view to its original size again. 

I tried to do: 

```
    var isGrowing = true
    self.badgeView?.transformScale()(2).animate()(3)
      self.badgeView?.animationCompletion = {
        if isGrowing {
          isGrowing = false
          self.badgeView?.badgeText = "\(self.selectionCounter)"
          self.badgeView?.transformScale()(1).animate()(3)
        }
    }
```

But it does not work that way. How can I fix this?

**Comment by jhurray** [comment]
Make the second animation 0.5 not 1

Also you should to set the animation completion before the animation. 

—

**Comment by jhurray** [comment]
You could also do transformIdentity.

**Comment by drmichaelgorski** [comment]
Thank you!

**Comment by drmichaelgorski** [comment]
What does transformIdentity do?

**Comment by jhurray** [comment]
Makes the transform value the identity, which means that it is not scaled, rotated or translated. I suggest reading up on cgaffinetransforns and catransform3d. They affect uiview and calayer respectively. 

—
