### ISSUE TITLE
easeInCirc

### ISSUE THREAD

**Issue by Zagash** [jhurray/JHChainableAnimations#16]
Hi,
trying to use **easeInCirc** effect I got a runtime error. With the same line of code but a different effect everything works fine.

`myView.moveXY(-20,-150).easeInCirc.makeScale(2.0).makeOpacity(1.0).animate(0.8);`

Error: file JHKeyframeAnimation.m line 166

> Assertion failed: (CGFloatIsValid(x) && CGFloatIsValid(y)), function void >CGPathAddLineToPoint(CGMutablePathRef, const CGAffineTransform *, CGFloat, CGFloat), file >Paths/CGPath.cc, line 265.

**Comment by jhurray** [comment]
@Zagash sorry for the super delayed response. Fixing now. Keep an eye out in the next week or 2 for a major release

**Comment by jhurray** [comment]
Fixed in v2.0.0. Marking as closed
