### ISSUE TITLE
Can I spring when scale is 1.0?

### ISSUE THREAD

**Issue by Milker90** [jhurray/JHChainableAnimations#19]
I want to spring like this:  
 self.myView.makeScale(1.0).spring.animate(1.0);

but myView not animation.

I like this. Thanks!

**Comment by jhurray** [comment]
1.0 will make the frame be exactly what it is. Are you trying to double it or does it have a transform?

—

**Comment by Milker90** [comment]
yes it's OK when set scale value is 2.0, and have not a transform.
I want spring animation, the scale value like this:
1.0 -> 1.1(maybe) -> 1.0

**Comment by jhurray** [comment]
myView.makeScale(x).spring.thenAfter(t).makeScale(1.0/x).animate(t);

—

**Comment by Milker90** [comment]
thanks
