### ISSUE TITLE
How to animate with UILabel?

### ISSUE THREAD

**Issue by RayPS** [jhurray/JHChainableAnimations#2]

**Comment by jhurray** [comment]
A UILabel is a subclass of UIView. You can call all of the same chainable properties an a label.

``` objective-c
self.myLabel.makeBackground([UIColor redColor]).animate(1.0);
```

**Comment by RayPS** [comment]
Thanks a lot!
Another question, can i use this in Today Extension?
i got an UILabel in Today Widget but seems doesn't work.

**Comment by jhurray** [comment]
Not sure how animations are interpreted in today extensions. From what I know they are pretty lightweight. Any place an animation will run, this library will work. 

—
