### ISSUE TITLE
How to achieve applying animation effects on "- (JHChainableBezierPath) moveOnPath;"

### ISSUE THREAD

**Issue by saru2020** [jhurray/JHChainableAnimations#21]

**Comment by jhurray** [comment]
Please read the readme before opening issues. 

```
Animation effects do not work on path movements.
```

**Comment by saru2020** [comment]
Oops. I did read that.
My question was different.
Sorry, if I didn't quoted my question elaborately. 

Here's my question:
Is there an alternative way to apply animation effects on the path movements?
Is it possible to achieve using CAKeyFrameAnimation? Or any other possible ways?
If yes, i thought i can contribute to your library.

**Comment by jhurray** [comment]
Oh ok gotcha... So Im using keyframe animations for all of this but it may be possible with CAMediaTimingFunctions? idk... feel free to look into it, fork my code, and create a pull request if you have anything to add!
