### ISSUE TITLE
Stop (cancel), pause, resume animation

### ISSUE THREAD

**Issue by abekert** [jhurray/JHChainableAnimations#24]
Hi! Thank you for so awesome animation library.

A wanted to ask you to add animation controlling features like **stopping**, **pausing** and **resuming** animations.

**Comment by jhurray** [comment]
@win2l I am thinking about updating this library in the next few months! still havent decided whether to keep it in obj-c or whether to move to swift yet though. those features will be included!

**Comment by abekert** [comment]
There are many Swift libs ([one](https://github.com/Draveness/DKChainableAnimationKit), [two](https://github.com/icanzilb/EasyAnimation), [three](https://github.com/alikaragoz/DaisyChain) and [counting](https://github.com/vsouza/awesome-ios#animation)).

I think, number of Swift libraries will be increasing, and there is a chance there will no any good animation library for Objective-C anymore if you switch.

**Comment by jhurray** [comment]
Added in v2.0.0. Marking as closed
