### ISSUE TITLE
Stop support for iOS 8/7?

### ISSUE THREAD

**Issue by bellchen** [jhurray/JHChainableAnimations#29]
the minimum deployment target is iOS9 which is declare in "JHChainableAnimations.podspec" file:
`s.ios.deployment_target = '9.0'`

**Comment by stefandragosnitu** [comment]
If you download the framework and add it to your project, it still works in iOS 8(tested).

**Comment by jhurray** [comment]
I will move the target down for `2.0.2` . Sorry about that!

**Comment by bellchen** [comment]
when the `2.0.2` will release ? any schedule？

**Comment by jhurray** [comment]
Whenever I get some free time in the next week or two. Feel free to submit a PR if its urgent and I'll review it

**Comment by AYastrebov** [comment]
@jhurray I've opened a [PR](https://github.com/jhurray/JHChainableAnimations/pull/34)

**Comment by jhurray** [comment]
Merged. Closing this issue
