### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by wuwen1030** [jhurray/JHChainableAnimations#3]
XCode throw an error " Use of '@import' when modules are disable", how should I solve the problem, thank you.

**Comment by jhurray** [comment]
Short answer change @import _; to #import "<_/*.h>" so @import UIKit; would be replaced with #import "<UIKit/UIKit.h>".

Im not sure if you have modules disabled on purpose or not. They are usually disabled when you are trying to run C++ code in your project. If you did not disable them on purpose, just enable them and the @import statements should work.

Also, this is a very general question that isn't specific to this library. In the future please look it up before you open an issue. 

**Related Links:**
[#import vs @import](http://stackoverflow.com/questions/18947516/import-vs-import-ios-7)
[example1](https://github.com/jessesquires/JSQMessagesViewController/issues/541)
[example2](https://github.com/dogo/SCLAlertView/issues/77)
