### ISSUE TITLE
Order of  callbacks

### ISSUE THREAD

**Issue by andrey-morozov** [jhurray/JHChainableAnimations#30]
Hi!
I test version 2 and found that the callbacks pre and post are called at the same time:
```
JHChainableAnimator *animator = [[JHChainableAnimator alloc] initWithView:self.label];
    animator.
    transformScale(0.01f).makeOpacity(0.0f).postAnimationBlock(@weakself(^() ){
        NSLog(@"postAnimationBlock %@",[NSDate date]);
    }@weakselfend).
    preAnimationBlock(@weakself(^() ){
        NSLog(@"preAnimationBlock %@",[NSDate date]);
    }@weakselfend).
    animationBlock(@weakself(^() ){
        NSLog(@"animationBlock %@",[NSDate date]);
    }@weakselfend).
    thenAfter(10.0f).
    postAnimationBlock(@weakself(^() ){
        NSLog(@"postAnimationBlock %@",[NSDate date]);
    }@weakselfend).
    animationBlock(@weakself(^() ){
        NSLog(@"animationBlock %@",[NSDate date]);
    }@weakselfend).
    preAnimationBlock(@weakself(^() ){
        NSLog(@"preAnimationBlock %@",[NSDate date]);
    }@weakselfend).
   transformScale(100.0f).makeOpacity(1.0f).animate(10.5f);
```
output:
> preAnimationBlock 2017-02-07 16:53:35 +0000
> animationBlock 2017-02-07 16:53:35 +0000
> postAnimationBlock 2017-02-07 16:53:35 +0000

> preAnimationBlock 2017-02-07 16:53:45 +0000
> animationBlock 2017-02-07 16:53:45 +0000
> postAnimationBlock 2017-02-07 16:53:45 

This is a bug or something I do not understand?

**Comment by jhurray** [comment]
@andrey-morozov that is for sure a bug. I actually think I see where this is going wrong in the code! will be fixed for `2.0.2`

**Comment by jhurray** [comment]
@andrey-morozov this seems to be indicative of a larger bug, I have to investigate further.

**Comment by abekert** [comment]
Hi! I found, that you fire _postAnimationBlock_ right after you commit animation transaction, but it's expected to call _postAnimationBlock_ inside the transaction's _completionBlock_.

Look at **JHAnimationChainLink** class, method _- (void)animateWithDuration:(NSTimeInterval)duration completion:(void (^)())completion_.

You call **[self executeCompletionActions];** after **[CATransaction commit];**. I moved this call into the _setCompletionBlock_ scope and it worked for me.

**Comment by abekert** [comment]
To call postAnimationBlock after animation finishes I add **thenAfter(0)** before **postAnimationBlock()**.

**Comment by jhurray** [comment]
Fixed here https://github.com/jhurray/JHChainableAnimations/pull/42
