### ISSUE TITLE
Chaining animations for multiple views

### ISSUE THREAD

**Issue by victorstewart** [jhurray/JHChainableAnimations#33]
any thoughts on being able to chain animations for multiple views in concert? both sequentially or simultaneously?

**Comment by stefandragosnitu** [comment]
use the delay feature.

**Comment by jhurray** [comment]
Theres no reason you shouldnt be able to add multiple views to an animator, it would be pretty easy to do this. thanks for the suggestion

**Comment by victorstewart** [comment]
I ended up figuring this out once I got my hands dirty with the library
