### ISSUE TITLE
Adding a .animationCompletion causes view to flash after animation finishes

### ISSUE THREAD

**Issue by andrewschreiber** [jhurray/JHChainableAnimations#4]
For example, given _myButton

self.myButton.animationCompletion = JHAnimationCompletion() {
NSLog(@"Done!");
});
self.myButton.makeX(5).animate(1.0);

And myButton will flash.

**Comment by dropski** [comment]
The same with anim without completion block, for example:

``` objective-c
self.makeOpacity(1).makeScale(2).animate(1);
```

**Comment by jhurray** [comment]
This is a known issue and is being worked on. It happens sometimes, not all the time.

A fix will be released soon along with some new chainable properties for 3D transitions and bezier paths

**Comment by jhurray** [comment]
This issue is now fixed. Thanks for the heads up.

**Comment by andrewschreiber** [comment]
Verified fixed! Thanks for the rapid update!

**Comment by dropski** [comment]
Confirmed! Works lika a charm :)
