### ISSUE TITLE
makeScale scales bounds

### ISSUE THREAD

**Issue by mxcl** [jhurray/JHChainableAnimations#9]
I was expecting it to apply a scaling CGAffineTransform.

Not many views scale well by adjusting their bounds, for me I was trying to scale a UILabel, which by default just truncates the text when smaller.

**Comment by jhurray** [comment]
A full suite of transform properties is in production

**Comment by jhurray** [comment]
Should work with transformScale. Pod version 1.3.0

**Comment by mxcl** [comment]
Your efforts are much appreciated.
